### PR TITLE
Fix broken link in README

### PR DESCRIPTION
**Pull request by lex111**
**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by childish-sambino** [comment]
@dprothero Looks like a tag mismatch. `oclif-dev readme` used `v2.0.0` but the tag is `2.0.0`. Maybe drop tag prefixes? `npm config set tag-version-prefix ''`

**Comment by lex111** [comment]
@childish-sambino thank you for correction! Fixed it.

**Review by childish-sambino — APPROVED** [review]
LGTM, but need to make sure the release process is correct.

**Comment by lex111** [comment]
I don’t know about this, I just noticed the broken link and decided to fix it.

**Comment by childish-sambino** [comment]
@lex111 Yup, the fix works. Just a note to @dprothero to look into the release process.

**Pull request merged**
